### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BossBele**
Important documentation for some React users; particularly those who use React with other frameworks eg. NextJS

### CODE REVIEW

**Comment by BossBele** [comment]
Important documentation for some React users; particularly those who use React with other frameworks eg. NextJS

**Review by joshuamshana — APPROVED** [review]

**Comment by BossBele** [comment]
@joshuamshana  Suddenly, README imefutika

**Comment by joshuamshana** [comment]
@BossBele hahaha haijafutika bwana iandike tena and create a pull request kuna changes nimezifanya za repo nikasahau kuibeba readme

**Comment by BossBele** [comment]
@joshuamshana  anhaaa, nshaweka PR nyingine #16

**Pull request merged**
